print ("TUTORIAL PARA BARRER UNA HABITACIÓN")
print ("===================================")
print ("\nMateriales:")
print ("- Escoba")
print ("- Aspiradora")
print ("- Contenedor de Basura")
print ("- Bolsa Negra para Basura")
print ("- Alzador de Basura")
print ("\nProcedimiento")
print ("1. Iniciamos recogiendo todos los objetos que no son basura (Ropa, cajas, libros, etc.)")
print ("2. Ahora con la ayuda de la escoba empezamos a barrer y agrupar la basura.")
print ("3. Empleando la escoba y alzador recojemos la basura y vertimos en el contenedor.")
print ("4. Aplicamos el paso 3 por cada agrupación existente.")
print ("5. Ahora que no hay basura procedemos a utilizar la aspiradora.")
print ("6. Es bueno definir zonas para no dejar lugar sin limpiar.")
print ("7. Ahora vamos a guardar todos los materiales excepto el contenedor de basura.")
print ("8. Vertimos toda la basura en la bolsa y amarramos.")
print ("9. Desechamos la bolsa con basura al camión de la basura.")
print ("10. Entramos a la habitación y observemos el cambio en la limpieza.")