print ("Penny: ¿Entonces los demas llegaran aqui?")
print ("Leonard: Si... No, es que Raj y Howard tenian trabajo y Sheldon tenía una colonoscopia y que no vuelve aun.")
print ("Penny: Mi tio tuvo una colonoscopía")
print ("Leonard: En serio, entonces es algo que tenemos en común.")
print ("Penny: ¿Y que hay de nuevo en la física?")
print ("Leonard: Nada")
print ("Penny: ¿En serio, nada?")
print ("Leonard: Bueno, con excepción de la teoria de la cuerda, no ha pasado mucho de los años 60, y no pueden probar esta teoria cuando mucho se dice -oye mira mi idea tiene una consistencia logica interna")
print ("Penny: Ah..., bueno todo saldra bien.")